import { NextPage } from "next";
import Head from "next/head";
import React from "react";
const Header: NextPage = () => {
  return (
    <Head>
      <title>test</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default Header;
